climatepolicyradar/data-access

src/cpr_data_access/models.py, tests/test_models.py
Added `Span` class and the relevant methods to `Document` as in the [Notion spec](https://www.notion.so/climatepolicyradar/Data-model-for-text-annotations-ef7bb538bb7c48b5a7ba05b609ed16a6).
There's also some barebones validation on the `Span` object to check we're not creating a instance that can't exist.
I've tried to make this self-explanatory via the docstrings so let me know if it isn't - I imagine we'll make small tweaks as soon as we start using this anyway.
=> Add span annotations to Document object

README.md, poetry.lock, pyproject.toml, src/cpr_data_access/data_adaptors.py, src/cpr_data_access/models.py, tests/test_data_adaptors.py, tests/test_models.py
see https://github.com/climatepolicyradar/explorer/pull/18
* base document metadata includes geography, as required by project specification in explorer
* `Dataset.load_from_remote` now takes the s3 path rather than just the bucket name
* added `Dataset.metadata_df` which produces a dataframe that can be used to get an easy overview of a dataset
=> changes to enable GST explorer run

src/cpr_data_access/models.py, tests/test_models.py
`CPRDocumentWithURL` was inheriting from `BaseDocument` rather than `CPRDocument`, so a load of metadata was going missing in the dataset metadata dataframe. 
Fixed and added a test.
=> Fix CPRDocument metadata model

src/cpr_data_access/models.py, tests/test_models.py
@henry-cpr i believe you asked for this the other day. second PR coming up to use this in explorer
=> functions to get text block window

src/cpr_data_access/models.py
There was validation in the `Span` object that checked that the text appeared from `start_idx:end_idx` in the sentence. This is incorrect – it should actually appear at `start_idx:end_idx` in the text block text. We don't store the text block text in the span object – only its hash – so I've removed this validation rather than replacing it with something else.
=> Remove erroneous span validation

src/cpr_data_access/models.py, src/cpr_data_access/parser_models.py
fixing an issue with loading outputs from the Google parser
=> add google to BlockType enum; remove copy of BlockType in models

.github/workflows/tag.yml
Copy of here: https://github.com/climatepolicyradar/azure-pdf-parser/pull/1
Add a workflow to add tagging of commits on pushes to pull request branches and merges to main. 
Please see the tag below:
=> RND-212 Add workflow to tag commits.

.github/workflows/tag.yml
Changing trigger so that we only run the tag workflow on a github tag. 
- We can update to be a proper semver tag if we like.
=> Changing trigger.

src/cpr_data_access/models.py, tests/test_models.py
When following the README instructions setting up this repo, two errors were thrown corresponding to the indexing and iterating over the `Dataset` object. This PR mitigates those errors by implementing the `__iter__()` and `__getitem__()` methods on `Dataset`.
- unit tests added for both methods
- retried running the README instructions successfully locally
=> Dataset object iterable and indexable

src/cpr_data_access/data_adaptors.py, src/cpr_data_access/parser_models.py
For data science purposes sometimes we want to parse documents we don't have metadata for 
This PR adds a `BaseParserOutput` class which assumes document metadata is just a dict. `ParserOutput` remains unchanged.
For typing purposes it may be better to define an `AnyParserOutput` for the methods which return `self` but this is just a sketch for now
=> new BaseParserOutput class with no document metadata assumptions

src/cpr_data_access/parser_models.py, tests/test_parser_models.py
---
Raise exception for failing to flip coords vertically. 
This exception is then defined in the data access library and can be caught by the indexer. 
We can then continue to index documents that pass this function and review the logs for documents that need fixing.
=> Adding exception to the method.

src/cpr_data_access/models.py, tests/test_models.py
- adds a new method to Dataset called `filter_by_corpus` to make it easier to filter by the source corpus name
- this relies on the assumption, that the document_id's are constructed as `"<corpus_name>.0000.0000.0"`
- by unit test: `test_dataset_filter_by_corpus`
=> Dataset - filter_by_corpus

pyproject.toml
note: version checking in CLI is also failing – it says `v0.1.10 == v0.1.10`
=> bump pyproject version

.github/workflows/check-version.yml, pyproject.toml, src/cpr_data_access/models.py
I've forgotten the exact error message, but if a token was provided in `**kwargs` to `Dataset().from_huggingface` then the kwarg would be duplicated in `load_dataset`, which would cause a script error.
This PR removes and replaces the `token` kwarg when setting instead of duplicating it
_edit: the version checking CI task was failing because `1.10<1.9`, so i've fixed this too_
=> fix 'two values have been provided for token argument' error; version check in CI

src/cpr_data_access/data_adaptors.py, src/cpr_data_access/models.py
- speeding up the loading of data from a local directory - this took up to 11 minutes on my machine (picture below)
- the symptoms get very bad for the whole corpus - load times are acceptable for smaller chunks of the dataset
- this is achieved through:
- excluding `html_data` and `pdf_data` from the `.dict()` method of the `ParserObject` in the document parser - this cut the document parsing time in half
- refactored and batched processing of the local files into `ParserObjects` - this reduced the data loading time
Digging into this, I've found that for processing the parsing of objects halts every now and then for _**minutes**_ sometimes. In addition, the memory footprint of the process is massive (see picture)
My suspicion was garbage collection being triggered because of the memory …
=> Speeding up the data loading

README.md, src/cpr_data_access/data_adaptors.py, src/cpr_data_access/exceptions.py, src/cpr_data_access/models/__init__.py, src/cpr_data_access/models/search.py, src/cpr_data_access/parser_models.py, src/cpr_data_access/search_adaptors.py, src/cpr_data_access/vespa.py, tests/test_search_requests.py, tests/test_search_responses.py
In a previous PR (https://github.com/climatepolicyradar/data-access/pull/48), we talked about replacing a few of the inappropriate `ValueError`s with some more descriptive/useful errors. This PR adds:
- a base `DataAccessError`
- `QueryError`, raised when a query can't be built
- `FetchError`, raised when the search engine fails to fetch results
- `DocumentNotFoundError`, raised when a document can't be found
Tests have been updated to use the new exceptions. As ever, running `make test` should run the whole suite.
- adds a missing `family_source` field to `Hit`
=> Custom exception hierarchy for search

src/cpr_data_access/parser_models.py
--- 
- Adds the block type `TableText` to support work in the azure pdf parser and the following linear ticket: 
https://linear.app/climate-policy-radar/issue/PDCT-531/tag-table-text-as-type-table-text
=> Adding table text block type.

src/cpr_data_access/parser_models.py
--- 
Updates the block name from `TableText` to `TableCell` as it is agreed that it is a better naming of the block.
=> Updating block name to table cell.

src/cpr_data_access/models/__init__.py, tests/test_data/valid/test_pdf.json
i wasn't sure how the parser version is added to `pipeline_metadata` but this should make the data available to us to be able to compare data quality across parser versions
=> add pipeline_metadata to BaseDocument model

src/cpr_data_access/parser_models.py, tests/test_parser_models.py
--- 
- Integrates a fix such that we raise the correct validation error. 
- Currently the construction of the ParserOutput object swallows validation errors on the PDFData field and throws a KeyError.   
- Added a failing test to recreate the error. 
- Fixed the object to raise the correct error. 
Deeper Explanation: 
- This bug was found when testing the latest version of the parser in the pipeline which was tagging the table text blocks. 
- I forgot to update the data access version in the db writer which meant the `TableCell` blocks failed validation as they weren't recognised due to not being declared in the `BlockType` enum. 
- Pydantic was thus failing to validate the `PDFData` field and thus it just wasn't present in the `values` in the `root_validator`. 
- In this instance we want …
=> Bug Fix - Raise Correct Exception 

src/cpr_data_access/pipeline_general_models.py
--- 
- Adds a slug as an update type as we need to update slugs when the name of the document changes. 
- This was raised during the following bug: https://linear.app/climate-policy-radar/issue/PDCT-556/mis-matched-slugs-in-vespa-search-responses
=> Adding slug as a UpdateType.

tests/test_models.py
This test suddenly started failing when run in github actions. Locally it still ran fine and the previous commit merged to main also passed successfully. It turned out to be related to the way the fixture was handling null values in test data defaulting to "en". This is pretty weird and we should decide if we want to return to explore this some more.
In the meantime, however, this fixes the test (which can unblock: https://github.com/climatepolicyradar/data-access/pull/98), first by splitting up the test cases to avoid them interfering with each other. Secondly by being more explicit about the languages we are working with when running the language filtering tests.
=> Fix flakey test

src/cpr_data_access/vespa.py, tests/test_search_requests.py
Backslashes are the escape character for vespa, and will cause a query to
raise an "Invalid query parameter" error from vespa when used directly
and a 500 error when used through from the backend
=> Sanitize backslashes from vespa searches

src/cpr_data_access/search_adaptors.py, src/cpr_data_access/vespa.py, tests/test_search_requests.py
Catch query errors. This is motivated by making it possible to feed back issues through the
api when this is called through the backend, rather than failing with an
internal server error.
Note that this only catches this expected error, there may be other ways
this fails that we may need to add in the future
Outstanding
=> Feature/pdct 614 handle vespa errors gracefully (Part one)

.github/workflows/pre-commit.yml, .github/workflows/test.yml, poetry.lock, pyproject.toml
This Pull Request: 
--- 
- Updates from using groups to extras as this allows for install in another pyproject.toml as per this [pull request.](https://github.com/climatepolicyradar/navigator-backend/pull/189)
- This is as it was raised that groups weren't suitable. 
**This will slightly change the command that is required to install the additional groups. Notably spacy was previously installed as extras. Vespa was previously a dependency group.** 
Install dev dependency group:
```--with dev```
Install all extras: 
```--all-extras```
Install individual extras: 
```
--with vespa 
--with spacy
--with vespa,dev,extras
```
=> Updating to use optional extras rather than groups.

src/cpr_data_access/models/search.py, src/cpr_data_access/vespa.py, tests/test_search_requests.py
This Pull Request: 
--- 
- The data access library SearchParameter object now accepts the correct values that it actually expects to exist in the vespa schema. 
- This way we convert the keyword values prior to running root validation on the pydantic type. 
- This work was triggered by a bug in the backend which is being developed [here](https://github.com/climatepolicyradar/navigator-backend/pull/197)
=> Updating to validate for different keys.

src/cpr_data_access/resources/sensitive_query_terms.tsv, src/cpr_data_access/search_adaptors.py, src/cpr_data_access/utils.py, src/cpr_data_access/vespa.py, tests/test_search_requests.py, tests/test_utils.py
This applies existing logic around sensitive search terms that currently is applied during opensearch queries and adds it for vespa queries.
=> Detect sensitive terms in queries

src/cpr_data_access/parser_models.py, src/cpr_data_access/pipeline_general_models.py
This Pull Request: 
--- 
- Adds reparse as an update type such that we can trigger reprocessing of documents. 
- We could use the source url update type but this would be confusing should there be no actual source url update.
=> Adding reparse as an update type.

src/cpr_data_access/vespa.py
There is currently an issue with keyword filtering with either multiple filters or none. Multiple will create a query looking for all of the items rather than any. Meaning empty queries that should have results. While none will return an error.
By way of example. A search parameter with the following keyword filters:
```
{'family_geography': ['AUS', 'BRN' ...]}
```
Produces a yql query like so:
```
and (family_geography contains "AUS")
and (family_geography contains "BRN")
and ...
```
This functionality is important for the backend region searches.
A related issue is the scenario where filters are:
```
{'family_geography': []}
```
This currently results in a query error, because the generated yql would be:
```
and ()
```
=> Fix country & region filtering

src/cpr_data_access/models/search.py, src/cpr_data_access/vespa.py, tests/test_data/search_responses/search_response.json, tests/test_search_adaptors.py, tests/test_search_responses.py
This surfaces the prev continuation token from the vespa response at both
the family and the passage level. This enables the ability to go to the
previous set of results.
=> Add previous continuation token

src/cpr_data_access/models/search.py, src/cpr_data_access/vespa.py, src/cpr_data_access/yql_builder.py, tests/test_search_adaptors.py, tests/test_search_requests.py, tests/test_search_responses.py, tests/test_yql_builder.py
Vespa does not allow the use of the order by clause in the grouping, this led to the sorting being done as part of the python post processing instead. Since the first iteration of this code I have managed to find an alternate way of doing grouping sorts within Vespa. This has two advantages, the first is to simplify some of our code, the second is to make queries with sorting on average up to 10% faster
=> Use vespa for sorting

src/cpr_data_access/utils.py
Searching a substring in a string was leading to false positives, this switches to search for actual term matches instead
=> Fix sensitive matching

src/cpr_data_access/models/search.py, src/cpr_data_access/yql_builder.py, tests/test_search_adaptors.py, tests/test_search_requests.py, tests/test_yql_builder.py
Queries return both documents and passages, so in order to successfully run an all_documents search, we'd need to filter out passages. This is a requirement for the backend, which performs `browse` requests that are not intended to include passages.As well as being potentially useful generally this change willl resolve a backend issue
where browse requests are including passages.
=> Add document only searches

pyproject.toml, src/cpr_data_access/utils.py, tests/test_search_adaptors.py, tests/test_search_requests.py, tests/test_utils.py
The sensitive query change led to performance benchmark failures in the backend. Compiling the regex match up front reduces the impact.
Also added a test to help catch this next time
=> Compile sensitive terms up front for performance
